# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

source "https://rubygems.org"

gem "sqlite3"
gem "pry"
# gem "sinatra-activerecord"
